name: CI devops 2022 EPF
on:
  push: 
    branches:  [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-backend: 
    runs-on: ubuntu-18.04
    steps:
    #checkout your github code using actions/checkout@v2.5.0
      - name: Checkout         
        uses: actions/checkout@v2.3.3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'


     #finally build your app with the latest command
      - name: Build and test with Maven
        run: mvn clean verify --file API/simple-api-main/simple-api
