name: CI devops 2022 EPF
on:
  push: 
    branches:  [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-backend: 
    runs-on: ubuntu-18.04
    steps:
    #checkout your github code using actions/checkout@v2.5.0
      - name: Checkout         
        uses: actions/checkout@v2.3.3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

  # define job to build and publish docker image
build-and-push-docker-image:
 needs: test-backend
 # run only when code is compiling and tests are passing
 runs-on: ubuntu-latest

 # steps to perform in job
 steps:
   - name: Checkout code
     uses: actions/checkout@v2

   - name: Build image and push backend
     uses: docker/build-push-action@v2 
     with:
       # relative path to the place where source code with Dockerfile is located
       context: ./API/simple-api-main/simple-api
       tags:  ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-epf/simple-api

   - name: Build image and push database
     uses: docker/build-push-action@v2 
     with:
       # relative path to the place where source code with Dockerfile is located
       context: ./BaseDonnées
       tags:  ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-epf/database


   - name: Build image and push httpd
     uses: docker/build-push-action@v2 
     with:
       # relative path to the place where source code with Dockerfile is located
       context: ./httpd
       tags:  ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-epf/httpd


     #finally build your app with the latest command
      - name: Build and test with Maven
        run: mvn clean verify --file API/simple-api-main/simple-api
