name: 
on:
  #to begin you want to launch this job in main and develop
  push:
    branches: 
  pull_request:

jobs:
  test-backend: 
    runs-on: 
    steps:
     #checkout your github code using actions/checkout@v2.3.3
      - uses: 

     #do the same with another action (actions/setup-java@v2) that enable to setup jdk 11
      - name: 
        

     #finally build your app with the latest command
      - name: 
        run: 